### ISSUE TITLE
Error when running the example script

### ISSUE THREAD

**Issue by lPauI** [georgedouzas/sports-betting#47]
```from sportsbet.datasets import SoccerDataLoader
dataloader = SoccerDataLoader(param_grid={'league': ['Italy'], 'year': [2020]})
X_train, Y_train, O_train = dataloader.extract_train_data(odds_type='market_maximum', drop_na_thres=1.0)
X_fix, Y_fix, O_fix = dataloader.extract_fixtures_data()

from sportsbet.evaluation import ClassifierBettor
from sklearn.dummy import DummyClassifier
bettor = ClassifierBettor(DummyClassifier())
bettor.backtest(X_train, Y_train, O_train)

bettor.bet(X_fix, O_fix)```


Traceback (most recent call last):
  File "C:\Users\lascu\Desktop\Analyse bot\main.py", line 3, in <module>
    X_train, Y_train, O_train = dataloader.extract_train_data(odds_type='market_maximum', drop_na_thres=1.0)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lascu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sportsbet\datasets\_base.py", line 388, in extract_train_data
    data = self._extract_train_data(drop_na_thres, odds_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lascu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sportsbet\datasets\_base.py", line 318, in _extract_train_data
    self._check_param_grid()
  File "C:\Users\lascu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sportsbet\datasets\_base.py", line 113, in _check_param_grid
    full_param_grid_df = pd.DataFrame(self._get_params())
                                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\lascu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sportsbet\datasets\_soccer\_combined.py", line 383, in _get_params
    FDSoccerDataLoader.get_all_params().param_grid
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lascu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sportsbet\datasets\_base.py", line 465, in get_all_params
    return cls._get_params()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\lascu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sportsbet\datasets\_soccer\_fd.py", line 499, in _get_params
    urls = _extract_csv_urls(base_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lascu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sportsbet\datasets\_soccer\_fd.py", line 97, in _extract_csv_urls
    el.get('href') for el in bsObj.find_all('a') if el.get('href').endswith('csv')
                                                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by clarence-ong** [comment]
I have this issue too. How did you get around it?
